services:
  db:
    image: lomarkomar/web-giris-db
    environment:
      POSTGRES_USER: postgres_svc
      POSTGRES_PASSWORD: P4ssW0rd123
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    expose:
      - 5432
    restart: always
    networks:
      - web-giris

  backend:
    image: lomarkomar/web-giris-backend
    ports:
      - "8080:8080"
    expose:
      - 8080
    networks:
      - web-giris
    environment:
      - DATABASE_URL=postgres://postgres_svc:P4ssW0rd123@db/db
    depends_on:
      - db
    restart: always
    command: run

  swagger-ui:
    image: lomarkomar/web-giris-swagger
    ports:
      - "8081:8080"
    depends_on:
      - backend
    networks:
      - web-giris

networks:
  web-giris:
