services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres_svc
      POSTGRES_PASSWORD: P4ssW0rd123
      POSTGRES_DB: db
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    expose:
      - 5432
    restart: always
    networks:
      - web-giris

  backend:
    build: ./core
    ports:
      - "8080:8080"
    expose:
      - 8080
    networks:
      - web-giris
    environment:
      - DATABASE_URL=postgres://postgres_svc:P4ssW0rd123@db/db
    depends_on:
      - db
    restart: always
    command: run

  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    ports:
      - "8081:8080"
    volumes:
      - ./swagger:/swagger
    environment:
      - SWAGGER_JSON=/swagger/openapi.json
    depends_on:
      - backend
    networks:
      - web-giris

networks:
  web-giris:
