services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres_svc
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    restart: always
